# Generated by Django 5.1.5 on 2025-02-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_profile_profile_picture_meetuptodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
