# Generated by Django 3.2.12 on 2024-02-14 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pizza_cheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pizza_crust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pizza_sauce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pizza_size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pizza_order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('olives', models.BooleanField(default=False)),
                ('ham', models.BooleanField(default=False)),
                ('pineapple', models.BooleanField(default=False)),
                ('peppers', models.BooleanField(default=False)),
                ('extra_cheese', models.BooleanField(default=False)),
                ('mushrooms', models.BooleanField(default=False)),
                ('pepperoni', models.BooleanField(default=False)),
                ('chicken', models.BooleanField(default=False)),
                ('pizza_cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizza_cheese')),
                ('pizza_crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizza_crust')),
                ('pizza_sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizza_sauce')),
                ('pizza_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizza_size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
