# Generated by Django 3.2.12 on 2024-02-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_pizza_cheese_pizza_crust_pizza_order_pizza_sauce_pizza_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pizza_order',
            new_name='PizzaOrder',
        ),
    ]
