# Generated by Django 3.2.12 on 2024-02-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_rename_pizza_order_pizzaorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=12)),
                ('card_date', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
                ('PizzaOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizzaorder')),
            ],
        ),
    ]
