# Generated by Django 3.2.12 on 2024-02-20 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0005_remove_payment_pizzaorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='delivery_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
