# Generated by Django 5.1.5 on 2025-02-16 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='MeetupToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_to_meet', models.CharField(max_length=255)),
                ('meet_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_meetups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
